# Generated by Django 4.1.5 on 2023-01-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='название задания')),
                ('done', models.BooleanField(help_text='сделано')),
                ('created', models.DateTimeField(help_text='дата и время создания')),
                ('complited', models.DateTimeField(help_text='дата и время завершения')),
            ],
        ),
    ]
