# Generated by Django 4.1.5 on 2023-01-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod3hw1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='complited',
            field=models.DateTimeField(blank=True, help_text='дата и время завершения', null=True),
        ),
    ]
