# Generated by Django 4.1.5 on 2023-01-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod3hw1', '0003_alter_tasks_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name_plural': 'Tasks'},
        ),
    ]
