# Generated by Django 4.1.5 on 2023-02-21 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mod3hw1", "0004_alter_tasks_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasks",
            old_name="done",
            new_name="is_active",
        ),
        migrations.RenameField(
            model_name="tasks",
            old_name="name",
            new_name="title",
        ),
    ]
